name: Terraform & Python Lint CI

on:
  push:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      METABASE_PG_PASSWORD: ${{ secrets.METABASE_PG_PASSWORD }}
      SUPERSET_PG_PASSWORD: ${{ secrets.SUPERSET_PG_PASSWORD }}
      SUPERSET_SA_PASSWORD: ${{ secrets.SUPERSET_SA_PASSWORD }}
      SUPERSET_SECRET_KEY:  ${{ secrets.SUPERSET_SECRET_KEY }}
      CLICKHOUSE_SUPER_USER_PASSWORD: ${{ secrets.CLICKHOUSE_SUPER_USER_PASSWORD }}
      CLICKHOUSE_BI_USER_PASSWORD: ${{ secrets.CLICKHOUSE_BI_USER_PASSWORD }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.7.5'

      - name: Find and validate all Terraform projects
        id: tf-projects
        run: |
          # Найти все папки с main.tf, исключая игнорируемые .gitignore
          find . -type f -name 'main.tf' \
            | grep -vFf <(git check-ignore $(find . -type f -name 'main.tf')) \
            | xargs -I {} dirname {} | sort -u > tf_dirs.txt

          echo "Найдены Terraform директории:"
          cat tf_dirs.txt

          set +e
          failures=0
          while read -r dir; do
            echo "---- Проверка: $dir ----"
            cd "$dir"
            terraform fmt -check || failures=$((failures+1))
            terraform init -backend=false || failures=$((failures+1))
            terraform validate || failures=$((failures+1))

            VARS=""
            if [ -f variables.tf ]; then
              # Ищем все sensitive переменные (и только их)
              for var in $(awk '/variable /{gsub(/["{}]/,"",$2); name=$2} /sensitive *=[^=]*true/ {print name}' variables.tf); do
                secret_name=$(echo "$var" | tr '[:lower:]' '[:upper:]')
                # Добавляем только если секрет определён в окружении
                eval val=\$$secret_name
                if [ -n "$val" ]; then
                  VARS="$VARS -var=\"$var=$val\""
                fi
              done
            fi

            # shellcheck disable=SC2086
            eval terraform plan -out=tfplan $VARS
            rc=$?
            if [[ $rc -ne 0 && $rc -ne 2 && $rc -ne 3 ]]; then
              failures=$((failures+1))
            fi
            terraform show -no-color tfplan > "../$(basename $dir)_plan.txt" || true
            cd - >/dev/null
          done < tf_dirs.txt

          exit $failures

      - name: Upload Terraform plans as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plans
          path: ./*_plan.txt
        if: always()

  python-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Find and check Python scripts syntax
        run: |
          # Найти все .py-файлы, не игнорируемые .gitignore и не приватные
          git ls-files '*.py' ':!:additional/bi-infra/**/superset_config.py' ':!:additional/bi-infra/**/*config.py' ':!:additional/bi-infra/**/*secret.py' \
            | while read -r file; do
                echo "Проверка синтаксиса: $file"
                python -m py_compile "$file"
              done
