name: Terraform & Python Lint CI

on:
  workflow_dispatch: {}           # Ручной запуск с любой ветки для теста
  pull_request:
    branches:
      - master                    # Авто-проверка при создании PR на master
  push:
    branches:
      - master                    # Авто-проверка после мерджа в master

jobs:
  find-terraform-dirs:
    runs-on: ubuntu-latest
    outputs:
      tf_dirs: ${{ steps.set-dirs.outputs.tf_dirs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find Terraform directories
        id: set-dirs
        run: |
          # Найти все папки с main.tf, исключая игнорируемые .gitignore
          mapfile -t dirs < <(find . -type f -name 'main.tf' \
            | grep -vFf <(git check-ignore $(find . -type f -name 'main.tf') 2>/dev/null || true) \
            | xargs -I {} dirname {} | sort -u)
          echo "Найдены Terraform директории:"
          printf '%s\n' "${dirs[@]}"
          clean_dirs=()
          for d in "${dirs[@]}"; do
            d_clean=$(echo "$d" | xargs)
            [ -n "$d_clean" ] && clean_dirs+=("$d_clean")
          done
          printf '%s\n' "${clean_dirs[@]}" | jq -R . | jq -s . | tr -d ' \n' > tf_dirs.json
          echo "tf_dirs=$(cat tf_dirs.json)" >> $GITHUB_OUTPUT

      - name: Inspect tf_dirs.json
        run: |
          # Вывод содержимого tf_dirs.json для проверки
          echo "[INSPECT] Contents of tf_dirs.json:"
          cat tf_dirs.json

  terraform:
    needs: find-terraform-dirs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.find-terraform-dirs.outputs.tf_dirs) }}
    defaults:
      run:
        shell: bash
    env:
      BI_PASSWORD: ${{ secrets.BI_PASSWORD }}
      BI_USER_PASSWORD: ${{ secrets.BI_USER_PASSWORD }}
      CLICKHOUSE_BI_USER_PASSWORD: ${{ secrets.CLICKHOUSE_BI_USER_PASSWORD }}
      CLICKHOUSE_SUPER_USER_PASSWORD: ${{ secrets.CLICKHOUSE_SUPER_USER_PASSWORD }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      SA_PASSWORD: ${{ secrets.SA_PASSWORD }}
      SA_USERNAME: ${{ secrets.SA_USERNAME }}
      SUPERSET_SECRET_KEY: ${{ secrets.SUPERSET_SECRET_KEY }}
      SUPER_USER_PASSWORD: ${{ secrets.SUPER_USER_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.7.5'

      - name: Load sensitive variables from variables.tf
        id: load-vars
        run: |
          VARS=""
          if [ -f "${{ matrix.dir }}/variables.tf" ]; then
            # Получить список sensitive переменных с default-значением
            defaults=()
            while read -r line; do
              defaults+=("$line")
            done < <(awk '
              BEGIN { var=""; sensitive=0; has_default=0; }
              /variable / { if (var && sensitive && has_default) print var; var=$2; sensitive=0; has_default=0; }
              /sensitive *= *true/ { sensitive=1; }
              /default *=/ { has_default=1; }
              END { if (var && sensitive && has_default) print var; }
            ' "${{ matrix.dir }}/variables.tf" | tr -d '"{}')
            for var in $(awk '/variable /{gsub(/["{}]/,"",$2); name=$2} /sensitive *=[^=]*true/ {print name}' "${{ matrix.dir }}/variables.tf"); do
              skip=0
              for d in "${defaults[@]}"; do
                if [ "$var" = "$d" ]; then skip=1; break; fi
              done
              [ "$skip" = "1" ] && continue
              # Ищем любой секрет, совпадающий по имени (регистронезависимо)
              env_name=$(env | grep -i "^${var}=" | cut -d= -f1 | head -n1)
              if [ -z "$env_name" ]; then
                env_name=$(env | grep -i "^$(echo "$var" | tr '[:lower:]' '[:upper:]')=" | cut -d= -f1 | head -n1)
              fi
              if [ -n "$env_name" ]; then
                val=$(printenv "$env_name")
                VARS="$VARS -var=$var=\"$val\""
              fi
            done
          fi
          echo "[LOAD VARS] Loaded variables: $VARS"  # Комментарий: вывод загруженных переменных
          echo "vars=$VARS" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: |
          set -ex  # Включить подробный вывод и прерывание при ошибках
          echo "[TF INIT] Running terraform init in ${{ matrix.dir }}"  # Перед init
          terraform init -backend=false
          echo "[TF INIT] Completed terraform init"  # После init
        working-directory: ${{ matrix.dir }}

      - name: Terraform Validate
        run: |
          set -ex  # Включить подробный вывод и прерывание при ошибках
          echo "[TF VALIDATE] Running terraform validate in ${{ matrix.dir }}"  # Перед validate
          terraform validate
          echo "[TF VALIDATE] Completed terraform validate"  # После validate
        working-directory: ${{ matrix.dir }}

      - name: Terraform Format Check
        run: |
          set -ex  # Включить подробный вывод и прерывание при ошибках
          echo "[TF FMT] Running terraform fmt -check in ${{ matrix.dir }}"  # Перед fmt
          terraform fmt -check
          echo "[TF FMT] Completed terraform fmt -check"  # После fmt
        working-directory: ${{ matrix.dir }}

      - name: Terraform Plan
        run: |
          set -ex  # Включить подробный вывод и прерывание при ошибках
          echo "[TF PLAN] Running terraform plan in ${{ matrix.dir }}"  # Перед plan
          terraform plan -out=tfplan ${{ steps.load-vars.outputs.vars }}
          terraform show -no-color tfplan > plan.txt
          echo "[TF PLAN] Completed terraform plan and saved plan.txt"  # После plan
        working-directory: ${{ matrix.dir }}

      - name: Sanitize artifact name
        id: sanitize
        run: |
          dir="${{ matrix.dir }}"
          dir_sanitized=$(echo "$dir" | sed 's#^\./##' | tr '/.' '-' )
          echo "dir_sanitized=$dir_sanitized" >> $GITHUB_OUTPUT

      - name: Upload Terraform plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ steps.sanitize.outputs.dir_sanitized }}
          path: ${{ matrix.dir }}/plan.txt

  python-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Find and check Python scripts syntax
        run: |
          # Найти все .py-файлы, не игнорируемые .gitignore и не приватные
          git ls-files '*.py' ':!:additional/bi-infra/**/superset_config.py' ':!:additional/bi-infra/**/*config.py' ':!:additional/bi-infra/**/*secret.py' \
            | while read -r file; do
                echo "Проверка синтаксиса: $file"
                python -m py_compile "$file"
              done
